services:
  banking:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    command: yarn run start:dev
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${API_PORT}:${API_PORT}
  db:
    container_name: postgres
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}      
  dbadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    env_file:
        - .env
    ports:
      - 5050:80  
